### ISSUE TITLE
Cannot read properties from undefined (reading 'map')

### ISSUE THREAD

**Issue by LvffY** [cloud-carbon-footprint/ccf-backstage-plugin#13]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Azure Web App (I think Ubuntu, but not sure)
- **Browser:**
  - Chrome
### Expected Behavior

I should have my cloud carbon footprint estimation.

### Actual Behavior

I only get an error message withtout any of the estimation. But it seems that my Azure services are fetch correctly, so this could indicate that my Azure configuration is fine. 

### To Reproduce

- Use the last **Backstage** version
- Use the last **ccf-backstage-plugin** version
- Configure the azure connection

```yaml
cloudCarbonFootprint:
  client:
    dateRangeType: months
    dateRangeValue: 1
    groupBy: week
  azure:
    useBillingData: true
    clientId: ${AZURE_CLIENT_ID}
    clientSecret: ${AZURE_CLIENT_SECRET}
    tenantId: ${AZURE_TENANT_ID}
```

- Start the server, and go to the ccf page.

### Screenshots

- The error

![image](https://user-images.githubusercontent.com/37327656/189103567-4a21f8b8-dfba-4f95-a120-1abb6902226c.png)

- Logs
-
![image](https://user-images.githubusercontent.com/37327656/189103681-a2f08b3d-5504-4516-9ef5-63754f104ea9.png)

- The services (which seem to indicate my Azure resources, so the configuration should be fine)

![image](https://user-images.githubusercontent.com/37327656/189103867-1f7af6ed-17b5-4cf6-9e0f-3e5307d5887e.png)

### Additional Information

© 2022 Thoughtworks, Inc.
