### ISSUE TITLE
no data displayed for onPremise cloud provider

### ISSUE THREAD

**Issue by mthad** [cloud-carbon-footprint/ccf-backstage-plugin#6]
### Preflight Checklist

- [x ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (20H2)
- **Browser:**
  - Chrome

### Expected Behavior

Configured `CloudCarbonFootPrint` in `app.config.local` with the following settings according to the schema in `./config.d.ts` for `On Premise`:
```
# app.config.local:
cloudCarbonFootprint:
  client:
    dateRangeType: months
    dateRangeValue: 1
    groupBy: week
  onPremise:
    cpuUtilizationServer: 50
    avgWattsServer: 1000
```
- Expected to get data on the page `https:\\localhost:3000\cloud-carbon-footprint`
- Expected to see `On Premise` in  `cloud providers` filter at the top of the page

### Actual Behavior
- `On Premise` is not listed in `cloud providers` filter - (see screenshot below)
- got the message "There's no data to display!" - (see screenshot below)

### To Reproduce

- Install the plugin by following the official instructions
- configure app.config.local using the same data as above.

### Screenshots
- Cloud provider filter
![CloudProvides_Dropdown_list](https://user-images.githubusercontent.com/66381401/166422715-cf1010c6-bb9b-40df-ad7a-10412b6aa808.png)

- message displayed on the page `cloud-carbon-footprint`
![No_data_message](https://user-images.githubusercontent.com/66381401/166422885-68089f1c-9b13-49ff-87c7-c8d88845b556.PNG)

### Additional Information

© 2022 Thoughtworks, Inc.
