### ISSUE TITLE
Backstage Carbon Plugin: Add cache config on app-config.yaml 

### ISSUE THREAD

**Issue by jonathan-arenas-edo** [cloud-carbon-footprint/ccf-backstage-plugin#75]
Hi team,

I am working with the latest carbon footprint version:
```
@cloud-carbon-footprint/backstage-plugin-frontend@0.0.8
@cloud-carbon-footprint/backstage-plugin-backend@0.1.1
@cloud-carbon-footprint/common": "^1.11.0
```
Backstage version:
```
Version:
OS: Darwin 22.4.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli: 0.22.7 (installed)
backstage: 1.14.1
```

Configured backstage:
```
cloudCarbonFootprint:
      client:
        dateRangeType: years
        dateRangeValue: 1
        groupBy: week
      gcp:
        useBillingData: true
        billingProjectId: xxxxxxxxx
        billingProjectName: xxxxxxxxx
        bigQueryTable: billing.gcp_billing_export_v1_xxxxxxxxx
```
Is possible add the cache config on app-config.yaml? I want to use a GCS solution for cache storage:
For mongodb is possible, but for GCP is possible too?
https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/tree/trunk/plugins/backend#caching

Kind regards.

**Comment by 4upz** [comment]
Hi @jarenasla-edo, thanks for opening this issue! Are you able to provide a screenshot to help us understand what's going on?

To make sure I understand correctly, when loading the CCF page you see data for the breakdown charts and other components but not the usage graph? And recommendations indefinitely load?

**Comment by 4upz** [comment]
Sorry I believe I replied before you edited the issue. In regards to configuring a cache solution, this should already be accessible in the config. You can refer to this template to see where this would go: https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/plugins/backend/config.d.ts#L236

However, feel free to let us know if you have any trouble with configuring GCS with that variable. We're happy to troubleshoot if it gives you issues.

**Comment by jonathan-arenas-edo** [comment]
Hi @4upz , thanks for your comments.

I tested the GCS option but the system don't create a local cache file or without GCS, in local the file is not exists.
My problem is that the plugin need 30s to load data, and every time need anothers 30s for this reason I need implement the cache.

```
cloudCarbonFootprint:
      client:
        dateRangeType: months
        dateRangeValue: 6
        groupBy: month
      gcp:
        useBillingData: true
        billingProjectId: xxxxxxx
        billingProjectName: xxxxxxx
        bigQueryTable: billing.gcp_billing_export_v1_xxxxxxx
        gcsCacheBucketName: xxxxxxx-cache 
      optional:
        cacheMode: GCS
```
I watched on my events the next line:
`2023-06-22T16:23:17.739Z [Cache] info: Ignoring cache... `

Do you know because the system ignore the cache?
The option disableCache by default is false, is correct because I want enabled the cache.
https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/plugins/frontend/config.d.ts

Kind regards.

**Comment by 4upz** [comment]
@jarenasla-edo I appreciate the context, the cache is definitely helpful for reducing the load times. The app should not be ignoring cache by default. As a sanity check, have you tried explicitly setting `disableCache` to false in you config?

Additionally, would you mind providing an example of the request url that the client is making? You should be able to see it in your networking tab using your browser's debug tools.

Another possibility is that you may have had cache configured to previously be disable and have not restarted your app since changing the config.

**Comment by jonathan-arenas-edo** [comment]
Hi @4upz ,

Yes I reviews my config and the disableCache is false, but the request ignore the cache:
`cloud-carbon-footprint/footprint?start=2023-05-23&end=2023-06-23&ignoreCache=true&groupBy=month`

I restarted the app on each config change. (I use argocd to deploy new version) There are another config part on I need configure the cache?

Config file:

```
cloudCarbonFootprint:
      client:
        dateRangeType: months
        dateRangeValue: 6
        groupBy: month
        disableCache: false
      gcp:
        useBillingData: true
        billingProjectId: xxxxxxx
        billingProjectName: xxxxxxx
        bigQueryTable: billing.gcp_billing_export_v1_xxxxxxx
        gcsCacheBucketName: xxxxxxx-cache 
      optional:
        cacheMode: GCS
```

But the cache is not activate.
Can you tell me why this happens?

![Captura de pantalla 2023-06-23 a las 8 27 49](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/assets/118807917/58968704-7cac-408e-8677-fe1600d23783)
